repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
    -   id: check-ast
    -   id: check-json
    -   id: debug-statements
    -   id: detect-private-key
    -   id: check-case-conflict
    -   id: mixed-line-ending

-   repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-docstrings]
        args: [--max-line-length=127]

-   repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        args: ["--profile", "black", "--filter-files"]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.3.0
    hooks:
    -   id: mypy
        additional_dependencies: [types-requests, types-PyYAML]
        exclude: ^(docs/|tests/)

-   repo: https://github.com/zricethezav/gitleaks
    rev: v8.16.3
    hooks:
    -   id: gitleaks

-   repo: https://github.com/hadolint/hadolint
    rev: v2.12.1-beta
    hooks:
    -   id: hadolint
        files: ^docker/
        args: ['--ignore', 'DL3008', '--ignore', 'DL3013']