name: iRacing Data Collection

on:
  schedule:
    - cron: '0 */6 * * *'  # Every 6 hours
  workflow_dispatch:  # Manual trigger

jobs:
  collect-data:
    runs-on: ubuntu-latest
    
    env:
      IRACING_USERNAME: ${{ secrets.IRACING_USERNAME }}
      IRACING_PASSWORD: ${{ secrets.IRACING_PASSWORD }}
      POSTGRES_HOST: ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT: ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
      INFLUXDB_URL: ${{ secrets.INFLUXDB_URL }}
      INFLUXDB_TOKEN: ${{ secrets.INFLUXDB_TOKEN }}
      INFLUXDB_ORG: ${{ secrets.INFLUXDB_ORG }}
      INFLUXDB_BUCKET: ${{ secrets.INFLUXDB_BUCKET }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r python/requirements.txt
    
    - name: Run data collection
      run: |
        python python/collectors/iracing_collector.py
    
    - name: Upload logs as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: collection-logs
        path: iracing_collector.log