name: Docker Build

on:
  push:
    branches: [ main, master ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'docker/**'
  workflow_dispatch:

env:
  COLLECTOR_IMAGE_NAME: iracing-collector
  DASHBOARD_IMAGE_NAME: iracing-dashboard
  DOCKER_PATH: docker

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build collector image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ env.DOCKER_PATH }}/collector/Dockerfile
        push: false
        tags: ${{ env.COLLECTOR_IMAGE_NAME }}:test
    
    - name: Build dashboard image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: ${{ env.DOCKER_PATH }}/dashboard/Dockerfile
        push: false
        tags: ${{ env.DASHBOARD_IMAGE_NAME }}:test