name: Docker Security Scan

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'docker/**'
  schedule:
    - cron: '0 6 * * 1'  # Run every Monday at 6:00 AM UTC
  workflow_dispatch:

jobs:
  scan:
    name: Scan Docker Images
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build collector image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/collector/Dockerfile
        push: false
        load: true
        tags: iracing-collector:test
    
    - name: Build dashboard image
      uses: docker/build-push-action@v4
      with:
        context: .
        file: docker/dashboard/Dockerfile
        push: false
        load: true
        tags: iracing-dashboard:test

    - name: Run Trivy vulnerability scanner on collector
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'iracing-collector:test'
        format: 'sarif'
        output: 'trivy-collector-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Run Trivy vulnerability scanner on dashboard
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: 'iracing-dashboard:test'
        format: 'sarif'
        output: 'trivy-dashboard-results.sarif'
        severity: 'CRITICAL,HIGH'

    - name: Upload Trivy collector scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-collector-results.sarif'
        category: 'collector-container'

    - name: Upload Trivy dashboard scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v2
      if: always()
      with:
        sarif_file: 'trivy-dashboard-results.sarif'
        category: 'dashboard-container'