name: Python CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'python/**'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'python/**'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  PYTHON_PATH: 'python'
  MAX_LINE_LENGTH: 127
  MAX_COMPLEXITY: 10

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install -r ${{ env.PYTHON_PATH }}/requirements.txt
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ${{ env.PYTHON_PATH }}/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 ${{ env.PYTHON_PATH }}/ --count --exit-zero --max-complexity=${{ env.MAX_COMPLEXITY }} --max-line-length=${{ env.MAX_LINE_LENGTH }} --statistics
    
    - name: Test with pytest
      run: |
        # For this demonstration, we're just setting up the test structure
        # In a real setup, you'd run actual tests here
        # pytest ${{ env.PYTHON_PATH }}/tests/
        echo "Tests would run here if they existed"