name: Python CI

on:
  push:
    branches: [ main, master ]
    paths:
      - 'python/**'
      - '.github/workflows/python-ci.yml'
  pull_request:
    branches: [ main, master ]
    paths:
      - 'python/**'
      - '.github/workflows/python-ci.yml'
  workflow_dispatch:

env:
  PYTHON_VERSION: '3.10'
  PYTHON_PATH: 'python'
  MAX_LINE_LENGTH: 127
  MAX_COMPLEXITY: 10

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov
        pip install -r ${{ env.PYTHON_PATH }}/requirements.txt
    
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 ${{ env.PYTHON_PATH }}/ --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings
        flake8 ${{ env.PYTHON_PATH }}/ --count --exit-zero --max-complexity=${{ env.MAX_COMPLEXITY }} --max-line-length=${{ env.MAX_LINE_LENGTH }} --statistics
    
    - name: Test with pytest
      if: hashFiles('python/tests/*.py') != ''
      run: |
        pytest ${{ env.PYTHON_PATH }}/tests/ --cov=${{ env.PYTHON_PATH }} --cov-report=xml
      
    - name: Check test directory
      if: hashFiles('python/tests/*.py') == ''
      run: |
        echo "::warning::No test files found in python/tests/"
        echo "Test directory exists but contains no tests. Add tests for better code quality."
        
    - name: Upload coverage to Codecov
      if: hashFiles('python/tests/*.py') != ''
      uses: codecov/codecov-action@v5
      with:
        files: ./coverage.xml
        fail_ci_if_error: false
        verbose: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}